Enable ODB1+ODB2 when building mpas-bundle (#9)
Optionally enable ODB1+ODB2 when building mpas-bundle.
   1. Copied and modified two ODB set/build scripts from ioda/tools to mpas-bundle.
   2. Use the latest version of odb-api (0.18.0).
   3. Disable ctest when building ODB (slow to download test data).
   4. build/ctest passed on Cheyenne, but have some issues to build mpas-bundle in singularity. 
------
[ 97%] Linking CXX executable ../../bin/mpas_forecast.x
/usr/bin/ld: /home/vagrant/odb/install/lib/libodbmpiserial.a(mpi_alltoallv.F.o): undefined reference to symbol 'abor1_'
/home/vagrant/odb/install/lib/libodbifsaux.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
mpas/mains/CMakeFiles/mpas_forecast.x.dir/build.make:149: recipe for target 'bin/mpas_forecast.x' failed
make[2]: *** [bin/mpas_forecast.x] Error 1
CMakeFiles/Makefile2:9560: recipe for target 'mpas/mains/CMakeFiles/mpas_forecast.x.dir/all' failed
make[1]: *** [mpas/mains/CMakeFiles/mpas_forecast.x.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Linking CXX executable ../../bin/mpas_hofx.x
/usr/bin/ld: ../../lib/libioda.so: undefined reference to symbol 'abor1_'
/home/vagrant/odb/install/lib/libodbifsaux.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
mpas/mains/CMakeFiles/mpas_hofx.x.dir/build.make:149: recipe for target 'bin/mpas_hofx.x' failed
make[2]: *** [bin/mpas_hofx.x] Error 1
CMakeFiles/Makefile2:9431: recipe for target 'mpas/mains/CMakeFiles/mpas_hofx.x.dir/all' failed
make[1]: *** [mpas/mains/CMakeFiles/mpas_hofx.x.dir/all] Error 2
[ 97%] Linking CXX executable ../../bin/mpas_dirac.x
/usr/bin/ld: /home/vagrant/odb/install/lib/libodbmpiserial.a(mpi_alltoallv.F.o): undefined reference to symbol 'abor1_'
/home/vagrant/odb/install/lib/libodbifsaux.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
mpas/mains/CMakeFiles/mpas_dirac.x.dir/build.make:149: recipe for target 'bin/mpas_dirac.x' failed
make[2]: *** [bin/mpas_dirac.x] Error 1
CMakeFiles/Makefile2:9517: recipe for target 'mpas/mains/CMakeFiles/mpas_dirac.x.dir/all' failed
make[1]: *** [mpas/mains/CMakeFiles/mpas_dirac.x.dir/all] Error 2
[ 97%] Linking CXX executable ../../bin/mpas_parameters.x
/usr/bin/ld: /home/vagrant/odb/install/lib/libodbmpiserial.a(mpi_alltoallv.F.o): undefined reference to symbol 'abor1_'
/home/vagrant/odb/install/lib/libodbifsaux.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
mpas/mains/CMakeFiles/mpas_parameters.x.dir/build.make:149: recipe for target 'bin/mpas_parameters.x' failed
make[2]: *** [bin/mpas_parameters.x] Error 1
CMakeFiles/Makefile2:9474: recipe for target 'mpas/mains/CMakeFiles/mpas_parameters.x.dir/all' failed
make[1]: *** [mpas/mains/CMakeFiles/mpas_parameters.x.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
---------

List of files changed:
	modified:   build_mpas.csh
	new file:   run_odb_build.sh
	new file:   setup_odb_build.sh

Ctest on Cheyenne (one core) will have additional odb-related ioda tests:      
 5/10 Test  #5: test_ioda_locations_odb ...........   Passed    0.14 sec
 6/10 Test  #6: test_ioda_observationspace_odb ....   Passed    2.43 sec
 7/10 Test  #7: test_ioda_obsvector_odb ...........   Passed    2.62 sec
 8/10 Test  #8: test_ioda_locations_odb1 ..........   Passed    0.10 sec
 9/10 Test  #9: test_ioda_observationspace_odb1 ...   Passed    2.42 sec
10/10 Test #10: test_ioda_obsvector_odb1 ..........   Passed    2.68 sec